### PR TITLE
Add theValidatoR action

### PR DESCRIPTION
**Pull request by knightdave**
https://github.com/insightsengineering/automation-tasks/issues/162

### CODE REVIEW

**Comment by dinakar29** [comment]
@knightdave - theValidatoR is a [Dockerfile action](https://github.com/insightsengineering/thevalidatoR/blob/main/action.yml#L23-L26). We'll need to change the design for the action per https://github.com/insightsengineering/thevalidatoR/issues/29 and convert it to a composite action. Let's keep this open while we do that.

**Comment by knightdave** [comment]
> @knightdave - theValidatoR is a [Dockerfile action](https://github.com/insightsengineering/thevalidatoR/blob/main/action.yml#L23-L26). We'll need to change the design for the action per [insightsengineering/thevalidatoR#29](https://github.com/insightsengineering/thevalidatoR/issues/29) and convert it to a composite action. Let's keep this open while we do that.

Do we need to open some issue in validatoR or maybe you want me to convert it composite?

**Comment by dinakar29** [comment]
> Do we need to open some issue in validatoR or maybe you want me to convert it composite? I can reimplement it tomorrow morning

Yeah that would be great! Associated issue is https://github.com/insightsengineering/thevalidatoR/issues/29, as @dgkf-roche has mentioned - it needs to be reusable for any composition of R - so a composite action would be best suited for this.

**Comment by knightdave** [comment]
> > Do we need to open some issue in validatoR or maybe you want me to convert it composite? I can reimplement it tomorrow morning
> 
> Yeah that would be great! Associated issue is [insightsengineering/thevalidatoR#29](https://github.com/insightsengineering/thevalidatoR/issues/29), as @dgkf-roche has mentioned - it needs to be reusable for any composition of R - so a composite action would be best suited for this.

@dinakar29  - please give me then some minimal access to https://github.com/insightsengineering/thevalidatoR to be alble to create branch and PR

**Comment by knightdave** [comment]
Blocked by https://github.com/insightsengineering/thevalidatoR/issues/29. Will back to this PR after resolving this issue

**Comment by dinakar29** [comment]
New release of thevalidatoR now available: https://github.com/marketplace/actions/r-package-validation-report?version=v1.1.0

**Review by arkadiuszbeer — APPROVED** [review]
LGTM

**Review by tomszosz — APPROVED** [review]
looks fine

**Pull request merged**
