### PR TITLE
test

### PR DESCRIPTION
**Pull request by pawelru**
# Pull Request

### CODE REVIEW

**Comment by llrs-roche** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m7pr** [comment]
I see that action for this PR is green
https://github.com/insightsengineering/r.pkg.template/actions/runs/11816560697

**Comment by llrs-roche** [comment]
Yes, but now we need to test that the changes work on an actual PR: after help from Pawl to understand how it works, I temporary modified the github action on one of the PR where it fails: https://github.com/insightsengineering/teal/pull/1406/commits/69ac901149502d25466a6d1cae8783225808479c and re-run the actions.

If https://github.com/insightsengineering/setup-r-dependencies/pull/19 fixes the issues we need to ask for merging, if not iterate till the setup-r-actions is fixed.

**Comment by llrs-roche** [comment]
Thanks both for the help. At the end using a branch without @ and changing the testing PR from draft to ready for review worked well to test changes on the CI setup. 

As this has been [merged](https://github.com/insightsengineering/setup-r-dependencies/pull/19) and [released](https://github.com/insightsengineering/setup-r-dependencies/releases/tag/v1.4.2) on a rolling version it will be picked up by the teal repositories and this PR doesn't need to be merged.

**Pull request closed without merging**
